plugins {
    id("java-library")
    id("maven-publish")
    id("dev.kikugie.stonecutter")
    id("net.neoforged.moddev") version "2.0.144"
}

// ---------------------------------------------------------------------------
// Video playback
// ---------------------------------------------------------------------------
// FFmpeg is not bundled in the jar. The mod downloads the official ffmpeg (and
// ffprobe) build into the game folder on first launch — the same approach
// already used for yt-dlp — and shells out to the binaries (see MediaBinaries /
// FFmpegCli). This keeps the distributed jar small and avoids shipping native
// libraries for every platform.

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------
// Everything below comes from stonecutter.properties.toml. Version-specific
// tables are already flattened for the version this subproject builds, so
// `deps.neoforge` resolves to a different value in versions/1.21.1 and
// versions/1.21.4.
fun prop(name: String): String = project.property(name).toString()

val modId = prop("mod.id")
val modName = prop("mod.name")
val modLicense = prop("mod.license")
val modVersion = prop("mod.version")
val modGroup = prop("mod.group")
val apiVersion = prop("mod.api_version")
val loaderVersionRange = prop("mod.loader_version_range")

val minecraftVersion = prop("deps.minecraft")
val minecraftVersionRange = prop("deps.minecraft_range")
val neoVersion = prop("deps.neoforge")
val javaVersion = prop("deps.java")
// Empty for a Minecraft version Parchment has not published mappings for.
val parchmentVersion = prop("deps.parchment")

version = modVersion
group = modGroup

base {
    // Version-qualified so a full multi-version build does not overwrite itself.
    archivesName = "$modId-$minecraftVersion"
}

sourceSets.main {
    resources {
        // Include resources generated by data generators.
        srcDir("src/generated/resources")

        // Exclude common development only resources from finalized outputs
        exclude("**/*.bbmodel") // BlockBench project files
        exclude("src/generated/**/.cache") // datagen cache files
    }
}

repositories {
    // Parchment mappings — ModDevGradle does not register this repository itself.
    maven("https://maven.parchmentmc.org") {
        name = "ParchmentMC"
    }
}

// Per-version: Mojang shipped Java 21 for 1.21.1-1.21.11 and moved to Java 25
// in 26.1. Gradle provisions whichever toolchain is missing through the foojay
// resolver applied in settings.gradle.kts.
java.toolchain.languageVersion = JavaLanguageVersion.of(javaVersion.toInt())

// ---------------------------------------------------------------------------
// ModDevGradle
// ---------------------------------------------------------------------------
// Captured outside the runs block: inside it, `project` resolves to the
// deprecated Dependencies.getProject().
val runsRoot = layout.projectDirectory.dir("run")

neoForge {
    version = neoVersion

    // Parchment stops at 1.21.11; 26.x builds against NeoForge's mappings alone.
    if (parchmentVersion.isNotEmpty()) {
        parchment {
            minecraftVersion = parchmentVersion.substringBefore(':')
            mappingsVersion = parchmentVersion.substringAfter(':')
        }
    }

    //accessTransformers.from("src/main/resources/META-INF/accesstransformer.cfg")

    // The jar declares two mods in neoforge.mods.toml (the mod itself and its
    // public API); both are produced by the main source set, so both have to be
    // mapped here or FML cannot locate the API mod in a dev run.
    mods {
        create(modId) {
            sourceSet(sourceSets.main.get())
        }
        create("liasmediaplayerapi") {
            sourceSet(sourceSets.main.get())
        }
    }

    runs {
        configureEach {
            // Recommended logging data for a userdev environment.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")

            logLevel = org.slf4j.event.Level.DEBUG

            // Per-version game directories so worlds and configs of one target
            // never leak into another.
            gameDirectory = runsRoot.dir(name)
        }

        create("client") {
            client()
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
            programArgument("--nogui")
        }

        // Launches GameTestServer, runs all registered gametests, then exits.
        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            // 1.21.4 split the datagen run type into clientData/serverData.
            if (stonecutter.eval(stonecutter.current.version, ">=1.21.4")) clientData() else data()

            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath,
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Token replacements
// ---------------------------------------------------------------------------
// 1.21.11 moved to Mojang's official names. Two of those renames are pure
// token substitutions with no semantics at all — ResourceLocation alone is 7
// imports and ~30 usages across 9 files — so they are rewritten at generation
// time instead of being guarded by hand, exactly as PORTING.md §4.7 planned.
//
// The boolean is the *direction*: true rewrites the left token into the right
// one, false rewrites it back. The shared src/ tree therefore round-trips —
// switching the active version to 1.21.11 rewrites it to the new names, and
// switching back restores the old ones.
//
// Only add renames here that are unambiguous substrings project-wide. Anything
// that changes a signature or a call shape belongs in a //? guard.
stonecutter.replacements {
    string(stonecutter.eval(stonecutter.current.version, ">=1.21.11")) {
        // net.minecraft.resources.ResourceLocation -> .resources.Identifier
        replace("ResourceLocation", "Identifier")
        // net.minecraft.Util -> net.minecraft.util.Util (same class, new package)
        replace("net.minecraft.Util", "net.minecraft.util.Util")
    }

    // 26.1 renamed the GUI drawing API wholesale: the GUI is no longer drawn but
    // *extracted* into a render state, so GuiGraphics became GuiGraphicsExtractor
    // and its draw methods were renamed to match. The three below are exact
    // one-for-one renames with identical signatures, over 14 files and ~80 call
    // sites. Everything else 26.1 changed needed a real guard instead.
    //
    // The leading dot and open paren matter: they keep the *reverse* direction
    // honest. Replacing a bare "text" back into "drawString" would rewrite the
    // word wherever it appeared; ".text(" only ever appears as this call.
    string(stonecutter.eval(stonecutter.current.version, ">=26.1")) {
        replace(".drawString(", ".text(")
        replace(".drawCenteredString(", ".centeredText(")
    }

    // The type rename needs a regex rather than a plain substring, because
    // NeoForge kept ScreenEvent.Render.getGuiGraphics() under its old name while
    // changing what it returns. A blanket substring swap rewrites that call site
    // into getGuiGraphicsExtractor(), which does not exist. The lookbehind says
    // what is actually meant: rename the type, never the getter.
    regex(stonecutter.eval(stonecutter.current.version, ">=26.1")) {
        replace(
            "(?<!get)GuiGraphics", "GuiGraphicsExtractor",
            "GuiGraphicsExtractor", "GuiGraphics",
        )
    }
}

// The unit tests compile against Minecraft (Component & friends) but do not boot
// the game, so they only need the modding dependencies on their classpath — not
// the FML JUnit launcher that neoForge.unitTest would install.
neoForge.addModdingDependenciesTo(sourceSets.test.get())

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
val localRuntime by configurations.registering
configurations.runtimeClasspath.get().extendsFrom(localRuntime.get())

dependencies {
    // The Minecraft / NeoForge dependency itself is provided by ModDevGradle
    // through the neoForge { version = ... } block above — do not declare it here.

    // Video playback shells out to external ffmpeg/yt-dlp binaries downloaded at
    // runtime (see MediaBinaries), so there are no extra compile dependencies.

    // Unit tests
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
}

// Expands the declared properties in neoforge.mods.toml. A missing property
// results in an error. Properties are expanded using ${} Groovy notation.
tasks.withType<ProcessResources>().configureEach {
    val replaceProperties = mapOf(
        "minecraft_version" to minecraftVersion,
        "minecraft_version_range" to minecraftVersionRange,
        "neo_version" to neoVersion,
        "loader_version_range" to loaderVersionRange,
        "mod_id" to modId,
        "mod_name" to modName,
        "mod_license" to modLicense,
        "mod_version" to modVersion,
        "api_version" to apiVersion,
    )
    inputs.properties(replaceProperties)

    filesMatching(listOf("META-INF/neoforge.mods.toml")) {
        expand(replaceProperties)
    }
}

publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            artifactId = base.archivesName.get()
            from(components["java"])
        }
    }
    repositories {
        maven {
            name = "local"
            url = uri(rootProject.layout.projectDirectory.dir("repo"))
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-Xlint:deprecation")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

// ---------------------------------------------------------------------------
// IntelliJ run configurations
// ---------------------------------------------------------------------------
// ModDevGradle names the module of the run configurations it generates by
// joining the Gradle project path with dots: ":1.21.1" plus the "main" source
// set gives "Lia-s-media-player.1.21.1.main". IntelliJ reserves '.' as the
// module-name separator and rewrites it to '_' inside each path segment, so the
// module it actually creates is "Lia-s-media-player.1_21_1.main".
//
// Every Stonecutter subproject is named after a Minecraft version, so without
// the rewrite below every generated run configuration points at a module that
// does not exist. IntelliJ drops the reference silently and the configuration
// comes up as "module not specified", with the main class unresolvable and no
// classpath. MDG only sanitises spaces, not dots.
//
// This runs after MDG has populated the container, and is idempotent: a name
// whose segments hold no dots is left alone, so it stays correct if MDG ever
// fixes this upstream.
if (System.getProperty("idea.sync.active").toBoolean()) {
    val mdgModulePrefix = rootProject.name.replace(" ", "_") + project.path.replace(":", ".")
    val ideaModulePrefix = rootProject.name.replace(" ", "_").replace(".", "_") +
            project.path.split(":").filter { it.isNotEmpty() }
                    .joinToString("") { "." + it.replace(".", "_") }

    gradle.projectsEvaluated {
        val ideaProject = (rootProject.extensions.findByName("idea")
                as? org.gradle.plugins.ide.idea.model.IdeaModel)?.project
        val settings = (ideaProject as? ExtensionAware)
                ?.extensions?.findByType(org.jetbrains.gradle.ext.ProjectSettings::class.java)
        val runConfigurations = (settings as? ExtensionAware)
                ?.extensions?.findByName("runConfigurations")
                as? org.jetbrains.gradle.ext.RunConfigurationContainer
                ?: return@projectsEvaluated

        runConfigurations.withType(org.jetbrains.gradle.ext.ModuleRunConfiguration::class.java).all {
            val current = moduleName
            if (current != null && current.startsWith(mdgModulePrefix)) {
                moduleName = ideaModulePrefix + current.substring(mdgModulePrefix.length)
            }
        }
    }
}
