plugins {
    id("java-library")
    id("maven-publish")
    id("dev.kikugie.stonecutter")
    id("net.neoforged.moddev") version "2.0.144"
}

// The subproject is named "<mc>-neoforge", so Stonecutter's default property tag is that
// whole string and the ["1.21.1"] tables in stonecutter.properties.toml would not be
// flattened. Declaring the Minecraft version as a tag restores that.
//
// Only the version, never "neoforge": a tag is stripped from *any* segment of a property
// path, so a "neoforge" tag would turn `deps.neoforge` into `deps`. That is why the
// property tables are keyed by Minecraft version alone and the loader is encoded in the
// key name (deps.neoforge / deps.fabric_api) rather than in a [neoforge."1.21.1"] table.
stonecutter.properties.tags(stonecutter.current.version)

// ---------------------------------------------------------------------------
// Video playback
// ---------------------------------------------------------------------------
// FFmpeg is not bundled in the jar. The mod downloads the official ffmpeg (and
// ffprobe) build into the game folder on first launch — the same approach
// already used for yt-dlp — and shells out to the binaries (see MediaBinaries /
// FFmpegCli). This keeps the distributed jar small and avoids shipping native
// libraries for every platform.

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------
// Everything below comes from stonecutter.properties.toml. Version-specific
// tables are already flattened for the version this subproject builds, so
// `deps.neoforge` resolves to a different value in versions/1.21.1 and
// versions/1.21.4.
fun prop(name: String): String = project.property(name).toString()

val modId = prop("mod.id")
val modName = prop("mod.name")
val modLicense = prop("mod.license")
val modVersion = prop("mod.version")
val modGroup = prop("mod.group")
val apiVersion = prop("mod.api_version")
val loaderVersionRange = prop("mod.loader_version_range")

val minecraftVersion = prop("deps.minecraft")
val minecraftVersionRange = prop("deps.minecraft_range")
val neoVersion = prop("deps.neoforge")
val javaVersion = prop("deps.java")
// Empty for a Minecraft version Parchment has not published mappings for.
val parchmentVersion = prop("deps.parchment")

version = modVersion
group = modGroup

base {
    // Version- *and* loader-qualified: the same Minecraft version is built for both
    // loaders, so without the suffix the two jars would overwrite each other.
    archivesName = "$modId-$minecraftVersion-neoforge"
}

sourceSets.main {
    // The Fabric bridge imports Fabric API, which is not on this classpath. Whole files
    // that belong to one loader are separated by package and excluded here rather than
    // wrapped in a `//? if neoforge` guard: stonecutter.filters would not help, since it
    // only decides which files the preprocessor visits, not which ones javac compiles.
    java.exclude("**/platform/fabric/**")

    resources {
        // Include resources generated by data generators.
        srcDir("src/generated/resources")

        // Exclude common development only resources from finalized outputs
        exclude("**/*.bbmodel") // BlockBench project files
        exclude("src/generated/**/.cache") // datagen cache files
    }
}

repositories {
    // Parchment mappings — ModDevGradle does not register this repository itself.
    maven("https://maven.parchmentmc.org") {
        name = "ParchmentMC"
    }
}

// Java toolchain, -Xlint:deprecation, JUnit/Mockito and publishing are the same on both
// loaders and live in one place.
apply(from = rootProject.file("gradle/common.gradle.kts"))

// ---------------------------------------------------------------------------
// ModDevGradle
// ---------------------------------------------------------------------------
// Captured outside the runs block: inside it, `project` resolves to the
// deprecated Dependencies.getProject().
val runsRoot = layout.projectDirectory.dir("run")

neoForge {
    version = neoVersion

    // Parchment stops at 1.21.11; 26.x builds against NeoForge's mappings alone.
    if (parchmentVersion.isNotEmpty()) {
        parchment {
            minecraftVersion = parchmentVersion.substringBefore(':')
            mappingsVersion = parchmentVersion.substringAfter(':')
        }
    }

    //accessTransformers.from("src/main/resources/META-INF/accesstransformer.cfg")

    // The jar declares two mods in neoforge.mods.toml (the mod itself and its
    // public API); both are produced by the main source set, so both have to be
    // mapped here or FML cannot locate the API mod in a dev run.
    mods {
        create(modId) {
            sourceSet(sourceSets.main.get())
        }
        create("liasmediaplayerapi") {
            sourceSet(sourceSets.main.get())
        }
    }

    runs {
        configureEach {
            // Recommended logging data for a userdev environment.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty("forge.logging.markers", "REGISTRIES")

            logLevel = org.slf4j.event.Level.DEBUG

            // Per-version game directories so worlds and configs of one target
            // never leak into another.
            gameDirectory = runsRoot.dir(name)
        }

        create("client") {
            client()
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
            programArgument("--nogui")
        }

        // Launches GameTestServer, runs all registered gametests, then exits.
        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            // 1.21.4 split the datagen run type into clientData/serverData.
            if (stonecutter.eval(stonecutter.current.version, ">=1.21.4")) clientData() else data()

            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath,
            )
        }
    }
}

// The unit tests compile against Minecraft (Component & friends) but do not boot
// the game, so they only need the modding dependencies on their classpath — not
// the FML JUnit launcher that neoForge.unitTest would install.
neoForge.addModdingDependenciesTo(sourceSets.test.get())

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
val localRuntime by configurations.registering
configurations.runtimeClasspath.get().extendsFrom(localRuntime.get())

dependencies {
    // The Minecraft / NeoForge dependency itself is provided by ModDevGradle
    // through the neoForge { version = ... } block above — do not declare it here.

    // Video playback shells out to external ffmpeg/yt-dlp binaries downloaded at
    // runtime (see MediaBinaries), so there are no extra compile dependencies.

    // JUnit and Mockito come from gradle/common.gradle.kts.
}

// Expands the declared properties in neoforge.mods.toml. A missing property
// results in an error. Properties are expanded using ${} Groovy notation.
tasks.withType<ProcessResources>().configureEach {
    val replaceProperties = mapOf(
        "minecraft_version" to minecraftVersion,
        "minecraft_version_range" to minecraftVersionRange,
        "neo_version" to neoVersion,
        "loader_version_range" to loaderVersionRange,
        "mod_id" to modId,
        "mod_name" to modName,
        "mod_license" to modLicense,
        "mod_version" to modVersion,
        "api_version" to apiVersion,
    )
    inputs.properties(replaceProperties)

    // Both metadata files live in the shared src/main/resources; each loader expands
    // and ships only its own.
    exclude("fabric.mod.json")

    filesMatching(listOf("META-INF/neoforge.mods.toml")) {
        expand(replaceProperties)
    }
}

// ---------------------------------------------------------------------------
// IntelliJ run configurations
// ---------------------------------------------------------------------------
// ModDevGradle names the module of the run configurations it generates by
// joining the Gradle project path with dots: ":1.21.1-neoforge" plus the "main"
// source set gives "Lia-s-media-player.1.21.1-neoforge.main". IntelliJ reserves
// '.' as the module-name separator and rewrites it to '_' inside each path
// segment, so the module it actually creates is
// "Lia-s-media-player.1_21_1-neoforge.main".
//
// Every Stonecutter subproject is named after a Minecraft version (plus its
// loader), so without the rewrite below every generated run configuration points
// at a module that does not exist. IntelliJ drops the reference silently and the configuration
// comes up as "module not specified", with the main class unresolvable and no
// classpath. MDG only sanitises spaces, not dots.
//
// This runs after MDG has populated the container, and is idempotent: a name
// whose segments hold no dots is left alone, so it stays correct if MDG ever
// fixes this upstream.
if (System.getProperty("idea.sync.active").toBoolean()) {
    val mdgModulePrefix = rootProject.name.replace(" ", "_") + project.path.replace(":", ".")
    val ideaModulePrefix = rootProject.name.replace(" ", "_").replace(".", "_") +
            project.path.split(":").filter { it.isNotEmpty() }
                    .joinToString("") { "." + it.replace(".", "_") }

    gradle.projectsEvaluated {
        val ideaProject = (rootProject.extensions.findByName("idea")
                as? org.gradle.plugins.ide.idea.model.IdeaModel)?.project
        val settings = (ideaProject as? ExtensionAware)
                ?.extensions?.findByType(org.jetbrains.gradle.ext.ProjectSettings::class.java)
        val runConfigurations = (settings as? ExtensionAware)
                ?.extensions?.findByName("runConfigurations")
                as? org.jetbrains.gradle.ext.RunConfigurationContainer
                ?: return@projectsEvaluated

        runConfigurations.withType(org.jetbrains.gradle.ext.ModuleRunConfiguration::class.java).all {
            val current = moduleName
            if (current != null && current.startsWith(mdgModulePrefix)) {
                moduleName = ideaModulePrefix + current.substring(mdgModulePrefix.length)
            }
        }
    }
}
